name: Build WaveXVZ APK
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v4
      - name: ⚙️ Setup Flutter (JALUR BETA)
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta' # KITA PINDAH KE KASTA BETA BIAR DARTNYA TINGGI!
      - name: 📦 Install Dependencies
        run: |
          flutter config --no-analytics
          flutter pub get
      - name: 🏗️ Build APK
        run: flutter build apk --release
      - name: 🚀 BUNGKUS APK
        uses: actions/upload-artifact@v4
        with:
          name: WaveXVZ-Kasta-Maestro
          path: build/app/outputs/flutter-apk/app-release.apk
